[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ejprd-onboarding-doc"
authors = [{name = "César Bernabé", email = "email@email"}]
dynamic = ["version", "description"]
